### ISSUE TITLE
Look at ea-async

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-sync#10]
https://github.com/electronicarts/ea-async seems to provide await/async similar construct but with less dependencies. Perhaps it could be used for implement vertx-sync too.

**Comment by rvraaphorst** [comment]
"The only requirement to use EA Async is that must be used only inside methods that return CompletableFuture, CompletionStage, or subclasses of CompletableFuture."

Having less dependencies is certainly nice. But this requirement requires all method signatures to reflect the async nature of the method. With quasar that's not the case.  Doesn't mean it's not worth looking at though.

**Comment by pron** [comment]
quasar-core really requires only a single dependency: ASM (maybe Guava, too). Everything else is for benchmarking and serialization, and can actually be made optional.
