### ISSUE TITLE
Performance between Vertx callbacks and Vertx sync

### ISSUE THREAD

**Issue by nishant-1984** [vert-x3/vertx-sync#14]
Can you elaborate how does the performance between vertx callback and vertx sync compare. Also explain any usecase  where vertx sync will not work. 

I have web application. One api call requires coordination between 5-6 microservices, some can be async and some have dependency on other.

Also in general how does vertx compare with ratpack?

**Comment by pmlopes** [comment]
This is not a issue, and for support you should ask on the official forum:

https://groups.google.com/forum/#!forum/vertx
