### ISSUE TITLE
Should we use quasar's jar specific to java8?

### ISSUE THREAD

**Issue by stephanebastian** [vert-x3/vertx-sync#4]
According to quasar documentation, there is a jar specific to jdk8.
http://docs.paralleluniverse.co/quasar/#maven

Since Vertx 3 requires at least java 8, it seems safe to explicitly require the following dependency in the pom:

```
<dependency>
    <groupId>co.paralleluniverse</groupId>
    <artifactId>quasar-core</artifactId>
    <version>0.7.2</version>
    <classifier>jdk8</classifier>
</dependency>
```

**Comment by pron** [comment]
If you're only supporting Java 8, then absolutely yes! It uses Java 8's built-in `ForkJoinPool` and `CompletableFuture` rather than jsr166's.
