### ISSUE TITLE
10x performance issues with Vert.x Sync compared to traditional Vert.x callbacks.

### ISSUE THREAD

**Issue by poiuytrez** [vert-x3/vertx-sync#9]
I noticed that Vert.x Sync is 10 times slower than traditional callbacks. I made a reproducer for this test by inserting 10,000 keys in Redis using both methods:

https://github.com/poiuytrez/vertx-sync-slow

**Comment by pron** [comment]
Are you running with the Quasar agent?

**Comment by poiuytrez** [comment]
Yes: 
/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java -javaagent:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/co.paralleluniverse/quasar-core/0.7.3/700f4769e54b9363d19b67f8d0913b1b76fae325/quasar-core-0.7.3-jdk8.jar -Didea.launcher.port=7533 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Users/poiuytrez/Documents/DataBerries/ads/random_stuff/slowsync/build/classes/main:/Users/poiuytrez/Documents/DataBerries/ads/random_stuff/slowsync/build/resources/main:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/io.vertx/vertx-core/3.1.0/52e7f3092becd8bae7a48779384ddcbe5d06757c/vertx-core-3.1.0.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/io.vertx/vertx-web/3.1.0/df8b2c3cc371bc496d7af28982353c72ae151aae/vertx-web-3.1.0.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/io.vertx/vertx-redis-client/3.1.0/f14b0145a930c5ab93cacec65fd9f865eea4d463/vertx-redis-client-3.1.0.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/io.netty/netty-common/4.0.31.Final/43de35e5da2c2aa57a3c50b633257b07d871aa09/netty-common-4.0.31.Final.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/io.netty/netty-buffer/4.0.31.Final/68d1c5030a2c7dccee85a1dd7a4ab442b7ece816/netty-buffer-4.0.31.Final.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport/4.0.31.Final/19d3545680718a880d16bd52076a471158b9929d/netty-transport-4.0.31.Final.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/io.netty/netty-handler/4.0.31.Final/61f50e42451104477d8903b9afff6421b6bdf9ac/netty-handler-4.0.31.Final.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-http/4.0.31.Final/bdc40b2b094a15f554e176b0602b2d9867e057ab/netty-codec-http-4.0.31.Final.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.6.1/892d15011456ea3563319b27bdd612dbc89bb776/jackson-core-2.6.1.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.6.1/45c37a03be19f3e0db825fd7814d0bbec40b9e0/jackson-databind-2.6.1.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/io.vertx/vertx-auth-common/3.1.0/4012e638eed760f580bd14539931b303306d7aed/vertx-auth-common-3.1.0.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec/4.0.31.Final/2c3b6af3fb5cbd5678d4d70601d8e0ec03170c6c/netty-codec-4.0.31.Final.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.6.0/a0990e2e812ac6639b6ce955c91b13228500476e/jackson-annotations-2.6.0.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/io.vertx/vertx-sync/3.1.0/7e891729dff0980aafae4f9dd6169e036ded52d9/vertx-sync-3.1.0.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/co.paralleluniverse/quasar-core/0.7.3/700f4769e54b9363d19b67f8d0913b1b76fae325/quasar-core-0.7.3-jdk8.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/io.dropwizard.metrics/metrics-core/3.1.2/224f03afd2521c6c94632f566beb1bb5ee32cf07/metrics-core-3.1.2.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/org.latencyutils/LatencyUtils/2.0.2/dcfce0d8b128638aa20e58697b1c40ff09e342db/LatencyUtils-2.0.2.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/de.javakaffee/kryo-serializers/0.36/c68dbc95c680ce783a4df4b3dd687e603e81dfe6/kryo-serializers-0.36.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/org.hdrhistogram/HdrHistogram/2.1.3/1ededfd6b2256151e082595ed0ef7ca5c4af464a/HdrHistogram-2.1.3.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/com.lmax/disruptor/3.3.2/8db3df28d7e4ad2526be59b54a1cbd9c9e982a7a/disruptor-3.3.2.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/18.0/cce0823396aa693798f8882e64213b1772032b09/guava-18.0.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/com.esotericsoftware.kryo/kryo/2.24.0/c6b206e80cfd97e66a1364003724491c757b92f/kryo-2.24.0.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java/2.6.1/d9521f2aecb909835746b7a5facf612af5e890e8/protobuf-java-2.6.1.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/com.esotericsoftware.minlog/minlog/1.2/59bfcd171d82f9981a5e242b9e840191f650e209/minlog-1.2.jar:/Users/poiuytrez/.gradle/caches/modules-2/files-2.1/org.objenesis/objenesis/2.1/87c0ea803b69252868d09308b4618f766f135a96/objenesis-2.1.jar:/Applications/IntelliJ IDEA 14.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain com.databerries.slowsync.MainClass

**Comment by pron** [comment]
Oh, got it. You're running two completely different tests. :)
Your callback test issues 10,000 requests in parallel and then waits for all of them to complete. Your sync test sends a request, waits for the response, and only then issues the next one.

To issue concurrent requests with Quasar, simply spawn a fiber for each one, call `awaitResult` in each, and in your test method, join all fibers.

To get the same behavior as your current sync test in the callback benchmark, you must issue the next request inside the callback.

**Comment by poiuytrez** [comment]
Is there an example on how to spawn and joins fibers ?

**Comment by pron** [comment]
Take a look at the [Quasar docs](http://docs.paralleluniverse.co/quasar/), but it will be something like:

``` java
long startTime = System.currentTimeMillis();

List<Fiber<Long>>> fibers = new ArrayList<>();

for (int i=0; i<10000; i++) // spawn fibers
    fibers.add(new Fiber<Long>(() -> awaitResult(h -> redisClient.setnx("foo", "bar", h)));

for (Fiber<Long> f : fibers) { // join fibers
    Long result = f.get();
    ...
}

System.out.println("We are done ! ");
long endTime = System.currentTimeMillis();
long diffTime = endTime - startTime;
System.out.println("diffTime = " + diffTime);
```

BTW, the above spawn code is identical to:

``` java
new Fiber<Long>(() -> {
         return awaitResult(h -> redisClient.setnx("foo", "bar", h));
     });

```

**Comment by pron** [comment]
BTW, if you're already familiar with the Vert.x coding style, I see no reason why you wouldn't be able to use callbacks when you need concurrent requests (though I personally prefer fibers) and use `awaitResult` when you really wish to block on a request.

**Comment by poiuytrez** [comment]
Thank you for providing the code. Unfortunately, it does not work and I don't know why. I do not get any error and the redisClient never gets call :(. 

I will continue to use the regular vert.x callback system with CompletableFutures on top of it. I read the Quasar in java 8 does use it so both solutions should be quite closed.

**Comment by purplefox** [comment]
As Ron says this is an apples vs oranges comparison.

In one example you are pipelining, in the other you are waiting for the reply from the previous operation before performing the next one. The performance difference here will be largely due to the latency of the redis call, not due to Quasar.

In the real world you would be unlikely to be inserting 10000 keys using vertx-sync in a single verticle, so it seems contrived to me.

**Comment by purplefox** [comment]
There should be no reason to manually create fibers. Each sync verticle invocation would be run using a fiber anyway. So in a real world example you'd have multiple verticle instances each doing a few inserts (not one verticle doing 1000s of inserts) and the performance between the sync and non sync cases should be very similar.

**Comment by poiuytrez** [comment]
You are right. I will close the ticket and make some more experiments with a real world scenario.
